const hooks = [
`How to make {thing} {positive outcome} in {exact time}.`,
`This might be the best way to...`,
`3 mistakes you might be making that... [insert negative result]`,
`Here are my real thoughts about...[insert something important or trending]`,
`Why [something] isn't working anymore`,
`Why [something] isn't enough`,
`Why your [insert method or tool] isn't working`,
`This might be one of the most important posts I've ever made (don't use this one a lot)`,
`I studied the top [insert method, tool or person type] and here's what I found`,
`I studied [insert number] of the best [insert method, tool or person type] and here's what I found`,
`The #1 thing you want to try if you want to [insert desired result]`,
`Here's how I... and how you can too`,
`How I finally... and how you can too`,
`If you're having trouble... I'm going to show you how to...`,
`3 Ways to quickly... [insert desired result]`,
`3 Easy ways to... [insert desired result]`,
`How to stop [insert negative problem]`,
`The quickest way to... [insert desired result]`,
`The best way to... [insert desired result]`,
`You'll want to know the best hack for... [insert desired result]`,
`You want to know this hack for... [insert desired result]`,
`If you want to...[insert desired result], then here's what to do`,
`If you're ready to...[insert desired result], then listen up`,
`3 simple ways to...[insert desired result] without [insert negative thing people want to avoid]`,
`How to...[insert desired result] without [insert negative thing people want to avoid]`,
`3 ways you know you're/you'll [insert desired result]`,
`You're going to want to know this crazy hack to...[insert desired result]`,
`If you want to be able to [insert desired result], then you'll want to follow these steps`,
`How to... [insert desired result] in 3 easy steps`,
`You might not like what I'm about to say`,
`3 reasons why... isn't working`,
`I'm about to tell you the truth about...`,
`Here's what...[insert person type, industry or organization] doesn't want you to know`,
`You might not like it, but you need to know the truth...`,
`Why you could be losing [insert something important] by [insert doing this activity]`,
`You might not like it, but [insert something people rely on] is changing. Here's what you need to know.`,
`You're being lied to (use this one with caution and don't name names)`,
`You said that if I did [this], I would get [that]. Here's the truth about [that]`,
`There's a lot of misinformation out there about [insert topic].`,
`I might get a lot of flack for this, but here goes... [insert controversial or surprising statement]`,
`People might not like what I'm about to say, but you need to hear it [insert controversial or surprising statement]`,
`So many people get this wrong... here's the truth about [insert topic]`,
`You shouldn't have to deal with [insert problem] in 2021. Here's what you can do about It.`,
`Did you know there's actually an easier way to...[insert desired result]`,
`Did you know most people don't know the best way to...[insert desired result]`,
`Things are not looking so good for... [insert person type, business or industry]. Here's what you need to know`,
`Crazy things are happening in the... [insert business, niche or industry] world. Here's what you need to know`,
`So you... [insert negative result or problem]? Here's what you can do about it.`,
`So you... [insert negative result or problem]? Here a 3 things you can do to fix it`,
`One of the best pieces of advice I ever heard/got was to [insert advice]. Here's how it change my life`,
`It breaks my heart when I see people... [insert negative result or problem]. Here's how to avoid it`,
`Stop doing [insert activity] to [insert desired result]. It doesn't work. Here's what to do instead.`,
`How the best [insert person type] are successfully/consistently [insert desired result or activity]`,
`The 3 best ways to consistently... [insert desired result or activity]`,
`Many people are experiencing...[insert negative result or problem]. Here's how you can avoid it`,
`We've all done it. [insert negative result, activity or problem]. But here's how to avoid it`,
`There's nothing wrong with you. We all experience...[insert negative result or problem]. Here's how you can fix it.`,
`If you're experiencing...[insert negative result or problem], it's probably not your fault. Here's what you need to know...`,
`I wasn't sure if I should share this, but here goes... [insert news or secret hack]`,
`I can't believe I'm about to share this... but here is the best way to [insert desired result].`,
`I can't believe I'm telling you this... but here's how I [insert desired result].`,
`I don't know about you, but I'm always looking for the best ways to...[insert desired result]. Here are 3 ways you can start [insert desired result] today`,
`3 ways you can start... [insert desired result] today`,
`3 things you must know if you want to...[insert desired result]`,
`3 things I wish I knew about... [insert topic] before I started`,
`You don't have to... [insert negative result or problem]. Here's what to do instead`,
`How 1 piece of advice changed my life.`,
`3 things you might not have known you can do with... [insert tool or platform]`,
`Most people don't know this secret hack for...[insert desired result]`,
`Most people don't know the most important step to...[insert desired result]`,
`It's finally here! [insert announcement or something exciting]`,
`We've all been waiting way too long. It's finally here! [insert announcement or something exciting]`,
`We've been asking for this for a while, and it's finally here [insert announcement or something exciting]`,
`You may have been wondering: How do I [insert desire]? Let me show you,`,
`The secrets to.. [insert desire] are being uncovered`,
`You're about to hear the secrets to.. [insert desire]`,
`The best kept secret to.. [insert desire] is finally being revealed`,
`3 things "they" don't want you to know about... [insert desire or industry]`,
`I followed the best advice about... [insert topic] Here's what I found...`,
`Have you heard about...? Here's what you need to know.`,
`If you haven't heard about... you're going to want to listen up.`,
`By now, you probably know that... Here's the inside scoop.`,
`You might have heard... Here's what you want to know.`,
`Are You Making This Common Mistake With X?`,
`3 Examples You Can Apply Immediately To Do X.`,
`The Step-By-Step Guide To X.`,
`How To X.`,
`Going through X and wanna cry? Here are 3 steps that can help.`,
`Did you know X? (X has to be some shocking statistic or interesting information.)`,
`If you're using X - ditch it right away.`,
`Wanna improve your X?`,
`Who else wants X?`,
`Why you're not getting X + how to fix it RIGHT AWAY.`,
`If you think that your X cares about Y, think twice.`,
`Wanna know an [industry] Secret to Y?`,
`You asked. Here's the answer. What's the difference between X and Y?`,
`**Alert!**Game Changer For Your X.`,
`What if I told you X? (X is something unusual or breaking the common belief.)`,
`An often-overlooked part of X. (And why it's crucial to Y.)`,
`If you want X to do Y, you've got to do Z. Here's how.`,
`Mind-Blowing Fact: [Write a shocking stat.]`,
`Do you feel frustrated because you squander money on X and don't see desired results?`,
`Do you want X, but can't figure out Y?`,
`Doing X and really want Y?`,
`The Top 3 Hacks To Improve X.`,
`Trying to do X (the thing that your target market really wants) while Y (difficulty, setback)?`,
`I'm answering the TOP question I get asked on social: [Insert the question that your audience is curious about.]`,
`How to turn X into Y.`,
`The only actual way to X?`,
`The #1 mistake I see people make with X is Y.`,
`What do X, Y & Z have in common?`,
`3 Hacks for Y (something that your target market really wants), even if Z (difficulty, setback):`,
`Why you always struggle to do X no matter how hard you try.`,
`Improve X with One Simple Technique.`,
`Do you think that X (ask something debatable)?`,
`If you've been told that the ONLY WAY to get X is to do Y, you've been MISLED. (Break the common belief.)`,
`What to do with X (And Chances Are It's Not What You Think It Is).`,
`What To Include In A Healthy Breakfast (And Chances Are It's Not What You Think It Is).`,
`X Ways I Increased My Y By Z (percentage) And So Can You:`,
`I average X and I only Y. (X and Y include numbers.)`,
`[Insert something your target market really wants to know about] is the question that I often get asked.`,
`"How can I X?" is the question that I often get asked.`,
`"Does X cause Y?" is the question that I often get asked.`,
`This X Year Old Y Trick Still Works.`,
`What makes a good X?`,
`To make your X MASSIVELY stand out from the crowd, do the opposite of what most people do.`,
`If your X doesn't do Y, you're doing it wrong.`,
`PRO TIP: How to make your X explode with one Simple Tactic.`,
`From starting X time ago to getting Y.`,
`3 Little-Known Steps to X:`,
`Don't know how to do X? Here's an evergreen piece of advice:`,
`How to get better at X? Try the Y FRAMEWORK:`,
`Succeeding with X is simple. Just follow these best practices:`,
`Not sure about X? Try this:`,
`When X, what happens to Y?`,
`What happens just before X?`,
`Are you missing these X in your Y?`,
`How to overcome X?`,
`The truth about X.`,
`What I wish I'd known about X at Y (age).`,
`Good or bad, X impacts Y.`,
`3 Stages of Y:`,
`Everybody knows X. What they don't know is Y.`,
`5 small things with a BIG EFFECT on X:`,
`One of the best X Frameworks to use if you want Y:`,
`Thinking about starting X? Here are X things to take into account before you start Y:`,
`X% of Y I see look like Z (something bad).`,
`How to MONETISE X?`,
`If you haven't done X, Y is a struggle.`,
`I'm convinced doing X is the best thing you can do for Y`,
`The cheat code for X`,
`I'm sure I'll get some hate on this but...`,
`A comment on one of my posts<br>[quote a shocking comment you've received]`,
`Do you know what kept me from doing  up until now?`,
`You don't need X to achieve Y.<br>Z is enough to Y. <br><br>Here's what I mean...`,
`A 90-second video on how to handle/overcome X:`,
`I ask myself these 3 questions before I X`,
`Master at least 2 of those 10 skills to work in X`,
`Average X:<br>[share something average in your industry]<br><br>Great copywriting:<br>[share a better way to do that thing from earlier or a short list of better alternatives.]`,
`There are many 'good' X. <br><br>But, what separates the 'good' from the 'great'?<br><br>Here's my take...`
]
