const touchpointsList = [
`Assets`,
`Automation`,
`Autononomy`,
`Positioning`,
`Building`,
`Community`,
`Communication`,
`Confidence`,
`Consequences`,
`Consistency`,
`Criticism`,
`Delegation`,
`Digital products`,
`Doubt`,
`Ego`,
`Entrepreneurship`,
`Execution`,
`Helping others`,
`Leverage`,
`Long game`,
`Momentum`,
`Money`,
`Networking`,
`Opportunity`,
`Promotion`,
`Publishing`,
`Responsibility`,
`Risk`,
`Sales`,
`Self-promotion`,
`Sharing`,
`Social Media`,
`Solopreneurship`,
`Success`,
`Systems`,
`Teamwork`,
`Thinking`,
`Time`,
`Work Ethic`,
`Writing`,
`Imagination`,
`Patience`,
`Calmness`,
`Time has a cost`,
`Be greedy`,
`Don't be greedy`,
`Progress`,
`Comfort`,
`Serve don't sell`,
`Risks`,
`Table Selection`,
`Learn to Build`,
`Grit`,
`Focus`,
`Obstacles`,
`Indecisiveness`,
`Be selective `,
`Mistakes`,
`Remedies`,
`Speed`,
`Fallibilism`,
`Inversion`,
`Doublespeak`,
`Talent vs. Genius`,
`Preference`,
`Biases`,
`Opportunity Cost`,
`Overton Window`,
`Bike-Shed Effect`,
`When to start`,
`Small wins`,
`Judgment`,
`Simplicity`,
`Ask`,
`Marketing`,
`Distractions`
];
