const tips = [
`Content is attention at scale and unlocks business growth.`,
`Repurpose anything good after 4 months. Nobody remembers.`,
`People want to be educated, entertained, or made to think.`,
`You need high-quality content but also great formatting.`,
`Attention is currency in the new digital economy.`,
`Shine the light on others to shine it on yourself.`,
`Give freely 80% of the time, and ask of your audience 20% of the time.`,
`When a piece of content works, study why.`,
`If you want people to engage, ask them to.`,
`Use data to inform what you write about.`,
`The opening line is 95% of your success.`,
`Master copywriting and master growth.`,
`Bring a unique perspective or blend in.`,
`Cut 30% of what you write.`,
`Study human psychology.`,
`Create for mobile first. It's where most people consume content nowadays.`,
`Build systems.`,
`If you want someone to do something ask.`,
`You don't need to be perfect. But you do need to be consistent.`,
`Don't be the critic.`,
`Without Promotion, Nothing Happens.`,
`Don't Be Afraid to Look Stupid`,
`The internet is an amplifier of people who pick themselves.`,
`Choose to Embrace Criticism, Not Praise`,
`Why are You Following the Crowd?`,
`Stop Being a Consumer of Social Media, Become a Creator`,
`Embrace, Discard, and Add`,
`Repetition unlocks value`,
`Discipline is your obstacle`,
`Competition is for Losers`,
`You aren't competing with anyone else but yourself.<br>Do better than you did yesterday.`,
`Look for Things That Don't Make Sense`,
`A few months from now, you'll wish you'd have started yesterday.`,
`Fools speak with the invincible authority of ignorance.`,
`Any movement forward is good. Even small steps.`,
`Learning can be your superpower`,
`Success is often the result of boring consistency applied to the right things.`,
`Outwork your self-doubt`,
`Creativity Favors the Unfocused`,
`Urgency is everything`,
`Ask for help`,
`The Map Is Not the Territory`,
`Comfort is the enemy of progress.`,
`Instead of selling, try serving.`,
`The default direction is not neutral.`,
`Negative comments are a positive signal: You learn more from what "doesn't work" than you do from what does work.`,
`Virality is an unsustainable dopamine hit.`,
`Imperfectly published > perfect but unpublished`,
`Visibility is more important than ability. Talented people who don't work very hard tend to not go anywhere. But "untalented" people who hit the pavement every single day can still become successful. You choose.`,
`The right way to create is often.`,
`Everyone is an expert in something.`,
`Evergreen content unlocks compounding benefits. Timely content does not.`,
`Consistency beats virality - people want to blow up the internet with 1 x post but few will stick it out long enough to see real growth.`,
`Connect with people relevant to your recruitment market - the people you really wanna do business with(don't waste time with randoms)`,
`Set aside 15 mins each day to engage with others, like and comment on no less than 10 posts`,
`Always aim to be positive, there is enough negative shit in the world`,
`Document don't create, base your content on stuff you ALREADY know and talk about daily.`,
`Commenting on someone's content almost ALWAYS leads to a conversation`,
`Debate but don't argue, life's too short to deal with trolls. The more you post the more some people won't agree- live with this and move on.`,
`Be personal, people love to connect to who you are inside and outside of work. How personal you get is up to you!`
]
