const strugglesList = [
  "is invloved in a difficult situation.",
  "is promised a great reward.",
  "falls in love at a very inconvient time.",
  "tries to make a grand gesture.",
  "makes a grand gesture.",
  "is compelled to exercise caution in an unsure situation.",
  "has to make a risky dicision in a dire situation.",
  "is involved in a hopeless love affair.",
  "encounters unforeseen obstacles.",
  "confronts a teammate over a difficult situation.",
  "is put to the test.",
  "suffers due to mistaken judgment.",
  "is confronted with a serious case of impostor syndrome.",
  "suffers a small but uncomfortable misfortune.",
  "loses something important to the mission.",
  "loses something personal.",
  "finds courage in misfortune.",
  "confesses a secret of transgression.",
  "loses something important to a teammate.",
  "bucks the authority of a superior and learns a lesson in humility.",
  "passes judgement hastily and suffers the consequences.",
  "is embarrased by a past transgression.",
  "learns of a plot against them.",
  "learns a new skill that ends up being surprisingly helpful.",
  "becomes involved in an unexpected complication.",
  "becomes the victim of mistaken identity",
  "tries to save a person who is falsely accused of a crime.",
  "secretly tries to save another from danger.",
  "refuses to betray a friend's secret.",
  "refuses to give up on a goal without a fight.",
  "finds peace in an unlikely place.",
  "takes a much needed break, but doesn't get the chance to relax.",
  "sets a goal that seems unattainable.",
  "annoys everyone else with a new hobby",
  "is having trouble processesing the loss of a loved one.",
  "develops a strange addiction.",
  "seeks out an old friend during a difficult time.",
  "faces a situation in which calls for great courage.",
  "has their faith in another tested.",
  "is forced to hide a devastating secret from the world.",
  "is forced to lie in order to save a loved one.",
  "enlists the help of an unexpected ally.",
  "seeks companionship in an unlikely place.",
  "is thrust into a painful situation.",
  "struggles with feelings of loneliness.",
  "bides their time while waiting on important information.",
  "is forced into hiding.",
  "has an epiphany.",
  "makes an important discovery.",
  "learns how to cook an old family recipe.",
  "thinks they are loosing their mind.",
  "has is injured in a major accident.",
  "has to conceal something important to save the mission.",
  "has an emotional breakdown in the aftermath of a tragedy.",
  "is made an irresistable offer.",
  "fights the urge to disobey a difficult order",
  "comes to terms with the death of a family member.",
  "resists an old addiction.",
  "embarks upon a personal quest.",
  "becomes involved in a complicated relationship.",
  "undergoes an experience that challenges known physics.",
  "undergoes an experience that challenges their most closely held beliefs.",
  "fails a friend.",
  "makes a mistake with dire consequences.",
  "sacrifices a personal goal to complete an obligation.",
  "is opposed by another teammate.",
  "mends an important bridge.",
  "solves a difficult puzzle.",
  "becomes indebted to an unscrupulous individual.",
  "struggles with personal limitations.",
  "must ask for help with a difficult obstacle.",
  "has an embarrassing personal problem.",
  "discovers the location of an important artifact.",
  "falls for a ruse.",
  "assumes a fake identity to save a friend.",
  "discovers a secret plot.",
  "devises a clever plan.",
  "saves the day.",
  "makes a costly mistake.",
  "is mixed up in a major crime.",
  "finds companionship in an unlikely place.",
  "falls ill of a mysterious sickness.",
  "unravels a secret ploy.",
  "mysteriously disappears.",
  "has a mystical experience.",
  "makes an unlikely connection.",
  "buys something new.",
  "eats something that doesn't agree with them.",
  "seeks advice from an old friend.",
  "is humbled.",
  "looses a bet.",
  "finds a lost treasure.",
  "has a strange dream.",
  "has to face a difficult challenge.",
  "pays a grim penalty in an unfortunate undertaking.",
  "emerges happily from a serious entanglement.",
  "emerges defeated from a serious entanglement.",
  "undertakes a role that leads straight to catastrophe.",
  "emerges from a trying ordeal with hard won wisdom.",
  "makes a hard sacrifice.",
  "corrects a wrong.",
  "mysteriously disappears.",
  "loses an old friend.",
  "struggles to maintain their integrity.",
  "struggles with an old adversary.",
  "faces off with an old teacher.",
  "searches for a guide.",
  "has a near-death experience",
  "has their confidence shaken",
  "makes a startling discovery",
  "finds some interesting information.",
  "bakes a cake.",
  "adopts an interesting pet.",
  "tries to learn how to sing.",
  "makes a deal with the devil.",
  "is a terrible liar.",
  "has a really bad poker face.",
  "makes a bad bet and loses.",
  "is put the the ultimate test.",
  "stages a rescue attempt.",
  "makes a dangerous discovery.",
  "stumbles upon an exciting discovery.",
  "learns how to whistle.",
  "buys a new shirt.",
  "has a new crush.",
  "can't catch a break.",
  "finally catches a break.",
  "has a close call.",
  "norrowly averts disaster.",
  "can't stand the new boss.",
  "can't feel their face.",
  "is feeling homesick.",
  "send a message to an old friend.",
  "gets acussed of stealing something important.",
  "loses an embarassing fight.",
  "breaks something important.",
  "gets lost... like, really lost.",
  "witnesses a crime but can't say anything.",
  "confronts an unexected foe.",
  "comforts an unexpected ally.",
  "is robbed, but the theives only took one thing.",
  "has to reveal a difficult secret."
];
