const summaries = [
  "An alien artifact transports {goodGuy.one} to an alternate reality, where they are not a part of {goodGuy.orgName} and the {badGuy.one} are invading {goodGuy.hq}.",
  "A mysterious affliction wipes out the entire population of a planet, plus a team from {goodGuy.orgName} - except for one young girl. {goodGuy.four} befriends her, but learns that she is being used by the {badGuy.one}.",
  "An alien artifact transports {goodGuy.two} to an alternate reality, where {goodGuycrewName} are not a part of {goodGuy.orgName} and the {badGuy.one}, led by {goodGuy.three}, are invading {goodGuy.hq}.",
  "{goodGuy.four} rebels against the social customs of an alien civilization after being kidnapped and traded to a tribal leader.",
  "{goodGuy.one} and {goodGuy.four} are separated from {goodGuy.two} and {goodGuy.three} during a long journey, and crash land on a desolate ice world with no way of escape.",
  "{goodGuy.two} is taken captive by an alien with a hidden agenda, while {goodGuy.crewName} is made to believe they are dead.",
  "{goodGuy.five} is possessed by a {badGuy.one} parasite, and {goodGuy.crewName} must find a way to remove it without killing them.",
  "Members of {goodGuy.crewName} become infected with an alien virus that turns them into primitive beings. the medical team must find a cure to save the team and the alien population from whom it was contracted.",
  "Pressed by {goodGuy.orgName} to acquire intel, {goodGuy.crewName} is led to a world inhabited by a seemingly primitive race. When {badGuy.one} arrives, {goodGuy.crewName} plan an ambush with disastrous consequences.",
  "A government representative arrives at {goodGuy.crewName} to investigate the program and determine whether the great drain on the {goodGuy.hq} budget is worthwhile, prompting the team to recall missions from the past year.",
  "{goodGuy.crewName} discovers a race of attractive people who age extremely rapidly. The situation becomes personal when {goodGuy.one} begins to suffer from the same accelerated aging, and must live out the rest of his life on the planet.",
  "{goodGuy.crewName} learns that {goodGuy.two}'s alternate reality vision is true when they transport onto {badGuy.one}'s attack ship headed for {goodGuy.hq}.",
  "{goodGuy.crewName} must stop a renegade {goodGuy.orgName} Commander, who has gone mad and set himself up as a god on an alien planet.",
  "{goodGuy.crewName} tracks down a reknowned scientist, who was lost long ago, and discovers an ancient meeting place that may hold the secrets of the universe itself.",
  "{goodGuy.three} and {goodGuy.one} are transported to an underground cage designed by the {ally.one} to protect an alien world from the {badGuy.one}. {goodGuy.three} cannot escape the labyrinth while his larval {badGuy.one} lives.",
  "{goodGuy.three} must stand trial for a crime committed whiletheyserved as a member of the {badGuy.one}'s slave army when a villager on an alien world identifies them as the one who killed his father.",
  "{goodGuy.three} returns to their homeworld to stop his people from brainwashing a family member into a {badGuy.one} slave, but a great sacrifice must be made to save them.",
  "A banished {badGuy.one} is found on an underdeveloped world, and takes over with hopes of raising a new army against the leadership of the {badGuy.one}.",
  "The {goodGuy.crewName} team rescues a group of advanced beings from a planet near destruction, and must find a new home for the refugees before the government gets their hands on them.",
  "The team discovers a crystalline alien species with the capability of assuming humanoid form. {goodGuy.one} comes to terms with the death of a family member.",
  "When powerful aliens come attack {goodGuy.hq}, {goodGuy.one} returns to {planet.five} to retrieve {goodGuy.two}, who has discovered that the alien transit system includes much more than the two planets.",
  "When {goodGuy.crewName} visits the underground warehouse of an advanced alien civilization, the area's caretaker transplants their minds into robotic duplicates - a 'gift' of immortality.",
  "A cosmic accident causes {goodGuy.crewName} to be sent back 30 years into {goodGuy.hq}'s past, where they must locate the {goodGuy.shipName} and find a way home.",
  "A group of primitive aliens begin to fall deathly ill after {goodGuy.crewName} arrives.",
  "A young boy arrives on {goodGuy.hq}, and warns of plot by invisible aliens to kill all of the inhabitants of {goodGuy.hq} in order to rob the {badGuy.one} of potential slaves.",
  "After gating to a world on the edge of a black hole, {goodGuy.crewName} cannot disengage the {goodGuy.shipName} -- threatening all of {goodGuy.hq} with a time-distorting gravity field.",
  "A {badGuy.one} leader, {goodGuy.crewName}'s greatest enemy, seeks sanctuary from a rival {badGuy.one} and ends up near death in {goodGuy.crewName} infirmary -- completely at the mercies of his human foe.",
  "{goodGuy.four} is contacted by a mysterious individual who claims to be an enemy of the {badGuy.one} and is being hunted by an assassin. In exchange for help the stranger has offered vital information that could help defeat the {badGuy.one}.",
  "{goodGuy.two} becomes addicted to the effects of a {badGuy.one} sarcophagus, and falls for the planet's manipulative princess.",
  "{goodGuy.two} discovers that a loved one has returned to their homeworld, and is about to give birth. {goodGuy.one} is approached by a reporter who threatens to expose {goodGuy.orgName} to the world.",
  "{goodGuy.one} becomes the unwilling receptacle for a library of alien knowledge, and ends up at an unlikely meeting with the {ally.one}.",
  "{goodGuy.one}, {goodGuy.four} and {goodGuy.two} awaken from stasis in what appears to be {goodGuy.hq} -- almost 80 years in the future -- and are asked to recall key events from their journeys.",
  "{goodGuy.crewName} discovers an ancient artifact that takes {goodGuy.crewName} hostage, infecting {goodGuy.one} with the remnants of a long-dead alien species.",
  "{goodGuy.crewName} discovers an elderly man known for developing technology to fight the {badGuy.one}, who tricks {goodGuy.two} into switching bodies with them -- the reward the man believes he is owed for his work.",
  "{goodGuy.crewName} finds a planet inhabited by Native Americans, protected by spirits who are actually advanced alien shape-shifters.",
  "{goodGuy.crewName} is accused of stealing an important peice of sacred technology, sending a primitive planet into chaos. The team discovers that the {goodGuy.orgName}'s ranks have been infiltrated by a rogue team.",
  "{goodGuy.crewName} is imprisoned in a virtual reality realm and forced to relive the worst moments of their lives over and over.",
  "{goodGuy.crewName} is put on trial and exiled to a prison world, where a woman maintains a strange control over their fellow prisoners.",
  "{goodGuy.crewName} locates the {ally.three}, a {badGuy.one} resistance movement who oppose the leadership of the {badGuy.one}, and attempt to form an alliance. {goodGuy.four}'s father's cancer brings him near death.",
  "{goodGuy.crewName} must stop the {badGuy.one}'s invasion force before it reaches {goodGuy.hq}, and escape with their lives.",
  "{goodGuy.crewName} returns to Cimmeria, and finds that without protection from the {ally.one} the planet has been invaded by the {badGuy.one}.",
  "{goodGuy.three} is infected with deadly venom from a giant insect, and begins a terrible transformation. After escaping {goodGuy.orgName}, {goodGuy.crewName} must find them before the government does.",
  "The {goodGuy.crewName} team attempt to rescue {goodGuy.three}'s family member, who has been kidnapped and brainwashed by {badGuy.one}. {goodGuy.three} learns disturbing news about a loved one.",
  "While {goodGuy.crewName} tries to form an alliance with the {ally.three}, a spy betrays the rebels to the {badGuy.one}. {goodGuy.four}'s father finds that the {ally.three} may be his only hope of survival.",
  "After a meteor strike buries the {goodGuy.shipName}, {goodGuy.one} finds himself stranded on a planet with no hope of rescue.",
  "An alien artifact causes {goodGuy.two} to disappear, and the team looks for help from his institutionalized grandfather -- unaware that their friend is still close by.",
  "Imprisoned on a hellish moon controlled by the {badGuy.one}, {goodGuy.crewName} and an ally are subjected to torture by one of their worst enemies.",
  "{goodGuy.one}, {goodGuy.three} and {goodGuy.two} are imprisoned on a planet and become pawns in a war of ideology, while {goodGuy.three} must rely on the kindness of a local man after being badly injured.",
  "{goodGuy.two} deals with the apparent death of a loved one at the hands of {goodGuy.three}.",
  "{goodGuy.one} steals technology from the {ally.three}, and is forced to leave {goodGuy.orgName}. A questionable ally offers an intriguing proposal involving his black-ops team.",
  "{goodGuy.one}, {goodGuy.four} and {goodGuy.two} must escape Ha{ally.one}'s clutches, while {goodGuy.three} tries to raise a {ally.two} army on Chulak. {goodGuy.boss} must take desperate measures to rescue the team.",
  "{goodGuy.crewName} discovers a military camp where young men are trained to impersonate {goodGuy.crewName} personnel to infiltrate {goodGuy.hq}.",
  "{goodGuy.crewName} discovers a planet of people with amnesia, and a familiar enemy returns to {goodGuy.hq} wearing an unfamiliar face.",
  "{goodGuy.crewName} discovers a planet where children are used to acquire knowledge for the entire population, then discarded.",
  "{goodGuy.crewName} discovers a mystical planet, and must find the child of a high powered {badGuy.one} official before the {badGuy.one}'s army does.",
  "{goodGuy.crewName} faces creatures of mass destruction that even the {ally.one} can't control, and must destroy an {ally.one} infested vessel before the {badGuy.three} reach {goodGuy.hq}.",
  "{goodGuy.crewName} finds a medieval society terrorized by {badGuy.one}, and is accused of being possessed by demons.",
  "{goodGuy.crewName} is taken captive by an alien bounty hunter with uncertain loyalties.",
  "{goodGuy.crewName} must find a renegade {badGuy.one} who has been hiding on {goodGuy.hq} for thousands of years.",
  "{goodGuy.crewName} must free an alternate reality {goodGuy.hq} from a {badGuy.one} invasion after duplicates of {goodGuy.four} and {goodGuy.five} come through the quantum mirror.",
  "{goodGuy.crewName} receives alien brain implants that manifest themselves as a bizarre man, who tells them that they would not survive the procedure to remove him.",
  "{goodGuy.crewName} returns from a mission and discovers that metamorphic aliens have taken over the complex.",
  "The {ally.one} aid {goodGuy.hq} in negotiating a non-aggression treaty with the leadership of the {badGuy.one}.",
  "The {ally.three} put the {ally.one} on trial to determine who will control a neighboring transit throughway, calling on {goodGuy.crewName} to defend their ally's claim against the {badGuy.one}.",
  "When {goodGuy.two} goes insane, {goodGuy.crewName} must deal with the legacy of {ally.two}'s anti-{badGuy.one} technology.",
  "When {goodGuy.four}'s father is kidnapped by {badGuy.one}, the {goodGuy.crewName} team must infiltrate a prison moon designed to look like hell to rescue him.",
  "A test gone wrong leaves {goodGuy.one} and {goodGuy.three} marooned in space aboard a damaged prototype attack ship.",
  "An archaeologist from the {ally.three} arrives at {goodGuy.hq} with newly discovered technology, giving the {goodGuy.crewName} team superhuman powers.",
  "A warring alien race offers to exchange their advanced technology for {goodGuy.hq}'s help in defeating their enemy.",
  "After {goodGuy.two} is taken captive by the {badGuy.one} while on an archaeological dig, {goodGuy.crewName} mounts a rescue operation -- but discovers a danger of their own.",
  "{goodGuy.four} must help keep a promising young cadet from throwing away a future at {goodGuy.orgName} {goodGuy.one} and {goodGuy.three} encounter a dangerous life form at an offworld research base.",
  "{goodGuy.two}'s teammates notice a disturbing change in them when  reunited with a previously dead loved one.",
  "{goodGuy.one} and {goodGuy.three} are caught in a time loop in {goodGuy.crewName}, and must relive the same 10 hours over and over again.",
  "{goodGuy.one} and {goodGuy.three} risk their lives to keep the {badGuy.three} from gaining a foothold on {goodGuy.hq}, while {goodGuy.four} helps the {ally.one} fend off a {badGuy.three} invasion.",
  "{goodGuy.crewName} finds a deserted {badGuy.one} palace, where a beautiful device causes suicidal tendencies.",
  "{goodGuy.crewName} helps to evacuate the {ally.three} to a new base -- but matters are complicated when a spy reveals their location to {badGuy.one}. The team attempts a daring plan to take out the {badGuy.one}'s powerful fleet.",
  "{goodGuy.crewName} investigates a conspiracy theorist who has detailed knowledge of the {goodGuy.orgName} secret projects.",
  "{goodGuy.crewName} is caught in a conflict between two civilizations trying to colonize the same planet.",
  "{goodGuy.crewName} joins forces with their robot doubles to rescue an alien world from the {badGuy.one}, while {goodGuy.three} seeks revenge for the murder of his father.",
  "{goodGuy.crewName} must adjust to a new commanding officer when {goodGuy.boss} steps down -- but {goodGuy.one} discovers foul play behind the general's resignation.",
  "{goodGuy.crewName} must stop {badGuy.one} and Heru'ur from forming an alliance of their powerful forces, while {goodGuy.three} is captured and tortured by the {badGuy.one}.",
  "{goodGuy.three} is reunited with a lost love who claims to have found a way to communicate with their future self and defeat the {badGuy.one}.",
  "Ten years into the future, the former members of {goodGuy.crewName} must send a message into the past to prevent the extinction of all who live on {goodGuy.hq}.",
  "The members of {goodGuy.crewName} are used as forced labor in an underground alien facility after their memories are erased by the ruling elite.",
  "{goodGuy.crewName} is put under quarantine after a mysterious infection leaves an officer of an ally in the infirmary -- but the disease may not be a disease at all.",
  "{goodGuy.crewName} is invaded by an alien life force that takes up residence in the base computer system -- and in {goodGuy.four}.",
  "When a member of {goodGuy.crewName} tries to kill a {ally.three}, it is revealed that {goodGuy.one} and {goodGuy.four} may be victims of an untraceable form of mind control.",
  "When a former mentor dies, {goodGuy.two} returns to their roots -- and discovers an ancient alien artifact containing a {badGuy.one} secret.",
  "A charismatic {ally.two} leader seeks to forge an alliance between {goodGuy.hq} and his rebel followers, winning the allegiance of {goodGuy.three} and Bra'tac.",
  "After an accident with the {goodGuy.shipName} traps {goodGuy.three} in transit, {goodGuy.crewName} must turn to an ally -- and to their enemies -- for help before time runs out.",
  "An alien being is smitten with {goodGuy.four} and follows them back to {goodGuy.hq}, assuming human form and pursuing a relationship.",
  "An alien ship approaches {goodGuy.hq}, sending {goodGuy.crewName} to an old friend for some answers -- where they discover that Martin Lloyd has created a TV show about {goodGuy.orgName}.",
  "{goodGuy.four} mysteriously falls ill, sending {goodGuy.crewName} back to their home planet -- where they uncover a dark {badGuy.one} secret.",
  "{goodGuy.two} is exposed to a lethal dose of radiation while visiting an alien civilization that is building a weapon of mass destruction.",
  "Dr. {goodGuy.one}son's undercover mission to a {badGuy.one} summit is complicated by the arrival of a surprise guest. Meanwhile, the rest of the team is buried under the surface of the {ally.three} homeoworld after a {badGuy.one} attack.",
  "{goodGuy.hq} finds itself threatened by something even larger than the {badGuy.one} when the team learns that an asteroid is on a collision course with the planet.",
  "His mind altered by a {badGuy.one}, {goodGuy.three} must undergo a ritual that takes them to the edge of death itself, in order to rediscover who they are.",
  "{goodGuy.one} and Lieutenant Tyler are ambushed by {badGuy.one} forces and trapped behind enemy lines -- while the rest of their team discover they don't know who Tyler is.",
  "{goodGuy.crewName} discovers a civilization that uses Unas as slave labor, and attempt to liberate {goodGuy.two}'s friend, Chaka.",
  "{goodGuy.crewName} discovers that their trip through the {goodGuy.shipName} may have inadvertently doomed an entire civilization, and plead with the {ally.one} for assistance.",
  "{goodGuy.crewName} encounters a potential new, technologically advanced ally in the war against the {badGuy.one} -- though they do not know the dark secret of the Aschen.",
  "{goodGuy.crewName} encounters a young woman with the ability to heal wounds and illness, and who may hold the key to the salvation of the {ally.one}.",
  "{goodGuy.crewName} finds themselves stranded in a crippled ship in a distant star system -- with the {badGuy.one} threatening to destroy them. {goodGuy.three} is suffers from a surprise case of PTSD.",
  "{goodGuy.crewName} must come to the rescue of their once-powerful allies when the {badGuy.one} attack a secret {ally.one} laboratory.",
  "{goodGuy.crewName} must turn to a pair of convicted criminals to save a world from annihilation by the {badGuy.one}.",
  "{goodGuy.crewName} teams with an ally unit when one of their crew goes missing on a mysterious alien planet.",
  "{goodGuy.crewName} trains a team of raw cadets, and {goodGuy.one} is forced to take them into a real-life battle situation when they learn of a possible alien incursion at {goodGuy.crewName}",
  "The {ally.two} send {goodGuy.two} to a secret meeting between the leadership of the {badGuy.one}, unaware that a new power is about to attack the {ally.two} homeworld.",
  "The {ally.three} offer {goodGuy.hq} advanced weapons technology, prompting a secret investigation on {ally.three} -- one that leads to a startling discovery.",
  "When {goodGuy.four} is kidnapped by a terminally ill man who intends to use  {badGuy.one} technology to save his life, {goodGuy.one} is forced to team up with an old foe to find their missing teammate.",
  "A near-death trial causes {goodGuy.three} to imagine their life as very different from the one they knows, where they are a normal person living on {goodGuy.hq} -- untiltheycan no longer distinguish reality.",
  "A news reporter threatens to expose a top-secret military project, but when {goodGuy.four} and {goodGuy.four} give her an exclusive on the technology, they discover that she is a pawn in a much larger plot.",
  "An alien world offers {goodGuy.hq} a medicine with the power to cure any illness -- but the hidden price may be too high to pay.",
  "{goodGuy.four} must find a way to save {goodGuy.hq} from total destruction at the hands of the {badGuy.one}, who have turned the {goodGuy.shipName} into a doomsday bomb. Rya'c joins his father on a mission to destroy the {badGuy.one} weapon.",
  "{goodGuy.four}, {goodGuy.three} and {goodGuy.four} investigate the death of a scientist with connections to the {badGuy.one}, and find a small town whose citizens harbor a dark secret.",
  "{goodGuy.one} is charged with the murder of A government representative, and the rest of the team must uncover a conspiracy in order to clear his name.",
  "{goodGuy.one} is trapped on an alien planet with an unsavory ally, and must fight to stay alive as his companion becomes increasingly paranoid.",
  "{goodGuy.boss} and the Government of {goodGuy.hq} reveal the existence of a secret weapon to other system governments, and must convince them that the technology will never be used against them.",
  "{goodGuy.four}' people ask {goodGuy.hq} for military aide in an impending war with their rival nations, but his former mentor offers another solution: a resistance movement ready for a coup.",
  "{goodGuy.one} is captured and tortured by the {badGuy.one} System Lord {badGuy.one}, and must rely on an old friend to survive.",
  "{goodGuy.shipName} is forced to land on an alien world, where a local starbase holds the team's only chance of returning home -- though the planet's population believe the space travel to be a myth.",
  "{goodGuy.crewName} attempts to save a planet's inhabitants from {badGuy.one}'s genetic experimentation, but find themselves to be the next victims.",
  "{goodGuy.crewName} boards an abandoned {badGuy.one} mothership that has mysteriously arrived in {goodGuy.hq}'s orbit, and must escape the doomed vessel when it crashes into the ocean.",
  "{goodGuy.crewName} investigates the discovery of a woman frozen in the ice in the southern most continent of the planet, who may be a link to a one lost past. A mysterious disease threatens to kill everyone at the research base.",
  "{goodGuy.crewName} is called to defend the people of a nearby planet from the {badGuy.one} once again when they learn that the {badGuy.two}, in search of a powerful device, is about to attack.",
  "Tensions rise between {ally.three} and {ally.two} teams when they are stranded on an old {goodGuy.orgName} outpost. Lurking in the shadows is an invisible enemy.",
  "The team finds an impoverished world enslaved by a {badGuy.one} underlord, but their plans to free it may be compromised when {goodGuy.four} experiences unexplained visions of the future.",
  "The team is called into battle unexpectedly when the {ally.one} {goodGuy.hq} is overrun by the {badGuy.three}s -- which have evolved into a startling new form.",
  "The team returns to {goodGuy.hq} with a piece of technology that allows them to see alien creatures everywhere, and must attempt to contain the problem when it spreads beyond the base.",
  "Tragedy reunites {goodGuy.three} with a family member, who blames them for the death of their mother. {goodGuy.one} and {goodGuy.four} launch a risky plan with untested technology when {goodGuy.hq} comes under attack by the {badGuy.one}.",
  "When {goodGuy.crewName} is captured by the {badGuy.one}, a pair of scientists mount a rescue operation ... whether they're wanted or not.",
  "When the team finds a crashed ship on another planet, their efforts to help the crew effect repairs are hindered by a group of aliens.",
  "A film crew arrives to document the work of {goodGuy.crewName} for eventual disclosure to the public, but finds that the base's personnel are less than eager to participate.",
  "A teenage boy shows up at {goodGuy.crewName} claiming to be {goodGuy.one}, sending the team on a mission to uncover his true identity.",
  "After an injury, {goodGuy.three} must put aside self-doubt when {goodGuy.crewName} launches a mission to rescue their family from a {badGuy.two} death camp.",
  "A scientist from {goodGuy.crewName} creates a computer virus to be used to disable enemy ships -- but succeeds in also disabling the ships of several important allies.",
  "The {badGuy.two} begins a systematic assault on {goodGuy.hq}, and the planet's only hope of salvation depends on whether {goodGuy.crewName} can find the Ancients' mythical Lost City.",
  "{goodGuy.four} is injured when {goodGuy.shipName} is attacked by an unknown ship, and awakens to find themself stranded alone in deep space.",
  "{goodGuy.two} is plagued by dreams of a former lover, who has been taken as a {badGuy.one} slave. {goodGuy.four} begins a romantic relationship with a detective, the detective becomes get in over their head and learns a life changing secret.",
  "{goodGuy.hq}'s secret offworld base is attacked by the {badGuy.two} forces, and {goodGuy.four} finds themself being hunted by the enemy. {goodGuy.boss} and Jacob {goodGuy.four} make an unnerving discovery about the {goodGuy.hq}-{ally.three} alliance.",
  "{goodGuy.four} joins an alien pilot for a space race, but the rest of the team discovers that on this world there is more at stake than the finish line.",
  "{goodGuy.one} goes to great lengths to keep the Ancients' knowledge from falling into {badGuy.one} hands when the team discovers a second repository. Meanwhile, the President replaces {goodGuy.boss} with a civilian diplomat.",
  "{goodGuy.one} seeks help from a former comrade to rescue {goodGuy.two} and a scientist, who have been kidnapped. {goodGuy.four}, {goodGuy.three} , and {goodGuy.four}'s father infiltrate the {badGuy.two} super-soldier facility.",
  "{goodGuy.crewName} discovers {goodGuy.two} alive and living on an alien world, with no memory of who they are. The team hatches a plan to lure the {badGuy.two} into a trap and destroy their new super-weapon.",
  "{goodGuy.crewName} investigates a secret {ally.three} laboratory, where a ruthless scientist has used cloning technology to create a {badGuy.one}-human hybrid.",
  "{goodGuy.crewName} is called into action while a film crew is documenting {goodGuy.orgName}, but {goodGuy.crewName} comes under investigation after the mission goes terribly wrong.",
  "The newly-elected President is debriefed about {goodGuy.orgName}, and the Vice President makes a new play for control of the program.",
  "The team finds a fugitive colony of {ally.two} women, who must prey on other {ally.two} to acquire desperately needed medical supplies.",
  "The team travels to a planet with a climate-controlled environment amidst a toxic wasteland, whose people are all linked to a central computer.",
  "The team returns to {goodGuy.five}'s homeworld when they learn that the {badGuy.one} are after its technology. When {goodGuy.four} is captured by the {badGuy.two}, {goodGuy.two} is their only hope.",
  "When {goodGuy.hq}'s attempts to exploit a newly-discovered mine are thwarted by a tribe of indigenous aliens, {goodGuy.crewName} must turn to an old friend for help.",
  "When {goodGuy.crewName} finds a crashed alien space ship, {goodGuy.two}'s mind is taken over by its disembodied passengers.",
  "When the {ally.four} discover that a massive underground vein of ore is being converted into a highly unstable explosive, {goodGuy.five} seeks help from {goodGuy.hq} in avoiding the total destruction of the planet.",
  "While {goodGuy.crewName} investigates a seemingly unstoppable new enemy soldier engineered by the {badGuy.two}, {goodGuy.two} leads a team in search of an alien device in Central America.",
  "A member of an alien species confronts {goodGuy.one}, claiming that they have been seeing visions of {goodGuy.crewName}'s missions over the last seven years.",
  "A businessman threatens to expose the secrets of alien life to the world, forcing {goodGuy.orgName} Command to bring him into the loop.",
  "A duplicate of {goodGuy.four} seeks help from {goodGuy.orgName} Command in defeating the {badGuy.three}, who they claim has found a way to counter the {ally.one}'s new weapon.",
  "After the {goodGuy.shipName} responds to a distress call from a {badGuy.one} ship, {goodGuy.two} finds himself a captive when {goodGuy.hq}'s ship is stolen.",
  "{goodGuy.four} and {goodGuy.three} go in search of the {ally.one} to try and save {goodGuy.one}, but discover that the {ally.one}'s enemy has returned with a vengeance. the leadership of the {badGuy.one} seek an alliance with {goodGuy.hq} against a common enemy.",
  "{goodGuy.two} is stranded on another planet after the team's arrival on an alien world sparks a violent civil war.",
  "{goodGuy.two} must once again decide whether to risk death facing their past or keep running from it, which could also prove just as deadly. {goodGuy.one} and {goodGuy.four} struggle with their respective personal relationships.",
  "General {goodGuy.one} tries to settle into a new job, but faces never-ending crises -- including the capture of {goodGuy.crewName} by the {badGuy.one}.",
  "Relations between the {goodGuy.hq} and an ally are strained when ally military leaders claim that the {goodGuy.hq} government has been compromised by the {badGuy.one}.",
  "{goodGuy.crewName} comes to the aid of a world about to be invaded by the {badGuy.one}, only to discover that the local king is a criminal from {goodGuy.hq}.",
  "{goodGuy.crewName} travels back in time in a daring plan to steal a piece of ancient technology from a powerful {badGuy.four} who ruled over a neighboring star system.",
  "{goodGuy.three} becomes the chief suspect in a murder investigation after they move into an apartment off-base. {goodGuy.four} considers a future with a new partner.",
  "{goodGuy.three} is trapped in a virtual reality simulation, in which they must defend the base from a {badGuy.one} super-soldier incursion.",
  "The fate of the galaxy hangs in the balance as {goodGuy.four} and a family member search for the only weapon capable of stopping the {badGuy.three} onslaught. {goodGuy.one} leads a defense of {goodGuy.crewName}, while {goodGuy.two} squares off against the {badGuy.three}.",
  "The impending wedding of a family member is the least of {goodGuy.three} 's worries when an uprising against {badGuy.one}, drives a wedge between {goodGuy.three} and their partner.",
  "the {badGuy.three} begin a systematic attack of the {badGuy.one}, forcing {badGuy.one} to come to {goodGuy.hq} for help. {ally.two} resistance risk their entire movement in an attempt to retake a holy city in {badGuy.one}'s domain.",
  "{goodGuy.crewName} is put under quarantine after a mysterious infection leaves an ally officer in the infirmary -- but the disease may not be a disease at all.",
  "the {goodGuy.shipName} is stolen, leading {goodGuy.crewName} to discover that A secret group has taken control of an advanced ship in orbit. {goodGuy.three} investigates a series of wide-spread {ally.two} deaths.",
  "While the {badGuy.one} threaten to attack {goodGuy.hq}, {goodGuy.crewName} and the {ally.one} make a last, desperate stand against the the {badGuy.three}, which have captured {goodGuy.four} and invaded the last outpost of the {ally.one} civilization.",
  "With the timeline changed by {goodGuy.crewName}'s actions in the distant past, an alternate version of {goodGuy.crewName} must use the newly-discovered time ship to set things right.",
  "A tour of an off-world research base for a group of foreign diplomats turns dangerous when an insidious insect species gets loose.",
  "{goodGuy.hqName} pilot attempts to reassemble {goodGuy.crewName} after they have gone their separate ways. An old 'friend' arrives on {goodGuy.hq} asking for {goodGuy.two}'s help in finding an ancient treasure -- and won't take no for an answer.",
  "An ancient communications device renders {goodGuy.two} and {goodGuy.five} unconscious, sending their minds to another galaxy -- where they inhabit the bodies of two people persecuted by the followers of an evil religion.",
  "As the {badGuy.four} plague spreads rapidly, {goodGuy.crewName} hopes that the Prior who caused the disease may hold the key to its cure. Gerak tries to rally {ally.two} to the {badGuy.four}'s cause, prompting {goodGuy.three} and Bra'tac to initiate a resistance.",
  "{badGuy.one} kidnaps {goodGuy.three} as part of a plot to brainwash those {ally.two} advocating a move toward democracy. {goodGuy.one}  learns that an old friend is about to die.",
  "{goodGuy.one}  is injured in a skirmish with a warrior from a mythic tribe of rebel {ally.two}, and is trained in their fighting techniques only so thattheymay engage in a ritual battle to the death.",
  "{goodGuy.one}  stands falsely accused of murder -- but surprisingly remembers committing it, thanks to technology that grafts memories into someone else's mind.",
  "{goodGuy.two} comes face to face with the {badGuy.four}, a fiery race of beings who demand the worship of mortals. Elsewhere, {goodGuy.orgName} Command encounters the first {badGuy.four} missionary in our galaxy.",
  "{goodGuy.two} is imprisoned on a world under the influence of the {badGuy.four}, and {shipName} is caught in a firefight when {goodGuy.crewName} tries to rescue him.",
  "{goodGuy.hq} is infected with a deadly {badGuy.four} plague, prompting an ally from {goodGuy.crewName}'s past to come to their aide. Leaders from {ally.two} propose a risky mission.",
  "{goodGuy.two} and {goodGuy.one} must join {goodGuy.five} on an interplanetary scavenger hunt when they learn that they are still bound together by an alien energy field.",
  "{goodGuy.one} and {goodGuy.four} are shifted to another dimension, making them invisible to everyone at {goodGuy.crewName} Meanwhile, {goodGuy.three} and SG-9 discover that the Sodan have been brutally attacked.",
  "Multiple {goodGuy.orgName} teams show up at {goodGuy.orgName} Command, leading the 'real' team to conclude that they have each been inadvertently displaced from different parallel realities.",
  "{goodGuy.four} returns to {goodGuy.orgName} Command when the {badGuy.four} seize control of a planet, using an expanding force field in an attempt to gain a foothold in our galaxy.",
  "{goodGuy.crewName} discovers the village of Camelot on an alien world, and must face an acient {ally.two}'s security system when they go in search of a long lost weapon. Elsewhere, {goodGuy.hq} and its allies assemble a fleet when a working {badGuy.four} battleship is discovered.",
  "{goodGuy.crewName} finds a genetically advanced {badGuy.one}-human hybrid created by the {badGuy.two}, and returns him to {goodGuy.hq} for study. But even keeping him alive may not be worth the risk.",
  "{goodGuy.crewName} is captured after a deal with the {badGuy.three} goes bad ... and the planet's leadership goes missing. Meanwhile, a former leader of the {badGuy.one} attempts to rebuild his empire.",
  "{goodGuy.crewName} must investigate when evidence suggests that there are still {badGuy.one} hiding on {goodGuy.hq} -- including a former leader of the {badGuy.one}. Tensions between {goodGuy.hq} and the {ally.two} continue to mount.",
  "{goodGuy.crewName} visits a world whose people once worshiped {goodGuy.five} as a god -- and demand that they stand trial when they confess to manipulating them.",
  "{goodGuy.five} makes contact with {goodGuy.orgName} Command from the {badGuy.four} home galaxy, and tells the story of her life undercover in a village of followers building the {badGuy.four}'s invasion fleet.",
  "An experiment gone wrong pulls {goodGuy.four} into a parallel reality, where they must save {goodGuy.hq} from an {badGuy.four} assault before they will be allowed to return home.",
  "As the {badGuy.four} invade {ally.two} planet Chulak, {goodGuy.five} and {goodGuy.two} must deal with their leader: {goodGuy.five}'s young daughter, rapidly aged by the {badGuy.four} to serve their purposes.",
  "{goodGuy.one}  must go undercover inside the deadly {badGuy.three} to prevent his teammates from becoming casualties of an Alliance civil war.",
  "{goodGuy.hq} provides sanctuary for {goodGuy.five}'s estranged, con artist father aftertheyprovide intel about a {ally.two} plot to attack the planet.",
  "An old friend seeks out {goodGuy.crewName} for assistance when his homeworld is attacked by a mysterious enemy.",
  "{goodGuy.crewName} hatches an elaborate plan to try and capture {badGuy.four}, using {goodGuy.five} as bait.",
  "{goodGuy.crewName} investigates a problem off-world and soon finds that they have become victims themselves: they cannot stay awake. Meanwhile, {goodGuy.five} Mal Doran undergoes an evaluation on {goodGuy.hq}, hoping to join {goodGuy.crewName}.",
  "{goodGuy.crewName} races against the {badGuy.one} in the hunt to find a long lost anti-{badGuy.four} weapon built by the {ally.two}, and comes up against a series of difficult trials.",
  "{goodGuy.crewName} realizes they have landed on a planet undergoing immense civil unrest and end up being mistaken for a band of zealous rebels who have taken hostages.",
  "{goodGuy.crewName} tries to defend a planet from the {badGuy.four} by hiding its people in another dimension. {goodGuy.five} attempts to convince a loved one of the {badGuy.four}'s true motives.",
  "{goodGuy.crewName} visits a distant star system in the hopes of preventing the {badGuy.four} from sending more ships into {goodGuy.orgName} space, and to find a new lead on important anti-{badGuy.four} technology.",
  "Stricken with amnesia and on the run, {goodGuy.five} takes a job as waitstaff at a diner on a backwater space station attempts to piece together who they are and what happened to their memories.",
  "{goodGuy.three} discovers a world where people are being savagely attacked by an elusive creature, leading {goodGuy.crewName} to a stunning discovery about its potential origin.",
  "{ally.two} take the fight to the {badGuy.four}, using a genocidal weapon on their new worshipers and landing {goodGuy.crewName} in the middle of a war they can't control.",
  "Trapped on board the Odyssey, the members of {goodGuy.crewName} must live out the rest of their lives together when {goodGuy.four} activates a time dilation field to save the ship from destruction.",
  "When a {badGuy.four} attack decimates a {ally.two} summit {goodGuy.three} strikes out on a quest for revenge, believing that the perpetrator is one of his own people.",
  "When {badGuy.one} comes to {goodGuy.hq} seeking help, {goodGuy.orgName} Command must capture his clones and determine which one is the genuine article.",
  "When {goodGuy.crewName} discovers that {goodGuy.two} has been seemingly brainwashed by the {badGuy.four}, they must determine whether or not his plan to destroy the {badGuy.four} is genuine.",
  "When the {badGuy.three} puts a bounty on {goodGuy.crewName}'s heads, {goodGuy.one} finds themself a target while attending a party.",
  "When the team finds an {ally.two} scientist, they must help him complete a weapon before {badGuy.four} forces can track them down."
];
